### ISSUE TITLE
pip install kivy

### ISSUE THREAD

**Issue by Dkzinho7** [LunaPy17/BulletDroid#2]
Error installing pip install kivy

**Comment by LunaPy17** [comment]
Can you send the error?

**Comment by Dkzinho7** [comment]
I can yes

**Comment by Dkzinho7** [comment]
nfig.h Updated /data/data/com.termux/files/usr/tmp/pip-install-vgispxf1/kivy_e247b68927b6402ca99474c9fc4169d1/kivy/include/config.h                                                                    Updated build/lib.linux-armv7l-cpython-311/kivy/include/config.pxi                                                              Updated /data/data/com.termux/files/usr/tmp/pip-install-vgispxf1/kivy_e247b68927b6402ca99474c9fc4169d1/kivy/include/config.pxi Updated build/lib.linux-armv7l-cpython-311/kivy/setupconfig.py Updated /data/data/com.termux/files/usr/tmp/pip-install-vgispxf1/kivy_e247b68927b6402ca99474c9fc4169d1/kivy/setupconfig.py Detected compiler is unix                                        error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1                       [end of output] note: This error originates from a subprocess, and is likely not a problem with pip.                                            ERROR: Failed building wheel for kivy Failed to build kivy                                            ERROR: Could not build wheels for kivy, which is required to install pyproject.toml-based projects

**Comment by Dkzinho7** [comment]
I'm getting this error when installing the requirements or when I try to install pip install kivy, and it's just me this error, my friends have tried it too and got the same error

**Comment by LunaPy17** [comment]
The project is not designed for Termux, for this there is the APK compiled in the [bin directory](https://github.com/LunaPy17/BulletDroid/blob/main/bin/bulletdroid-0.26-arm64-v8a_armeabi-v7a-debug.apk).
