### ISSUE TITLE
Failed building wheel for kivy

### ISSUE THREAD

**Issue by MajedurFahim** [LunaPy17/BulletDroid#3]
note: This error originates from a subprocess, and is likely not a problem with pip.                            
ERROR: Failed building wheel for kivy                 
Failed to build kivy                                    
ERROR: Could not build wheels for kivy, which is required to install pyproject.toml-based projects              ~/.../BulletDroid-main/BulletDroid-main $

**Comment by DannyLuna17** [comment]
Try again with a virtual environment.
